import sys
import re
file_path = r'c:\Users\PC\Downloads\proyecto-medico-ia\biologic-backend-modal\api_utils\gemini_core.py'
with open(file_path, 'r', encoding='utf-8') as f:
    content = f.read()

# Fix text-embedding-004 error
content = content.replace('model="text-embedding-004",', 'model="models/text-embedding-004",')
content = content.replace('model="models/text-embedding-004",\n                contents=text\n            )\n        except Exception as e:\n            print(f"[Embedding System] Error con text-embedding-004: {e}. Reintentando con models/text-embedding-004...")\n            res = await ai.aio.models.embed_content(\n                model="models/text-embedding-004",', 'model="models/text-embedding-004",\n                contents=text\n            )\n        except Exception as e:\n            print(f"[Embedding System] Error con text-embedding-004: {e}. Reintentando con models/embedding-001...")\n            res = await ai.aio.models.embed_content(\n                model="models/embedding-001",')

# Fix PASO 3
content = content.replace('"PASO 3 (Análisis Visual y Fenotipado Profundo): Analiza las imágenes. Detalla anomalías en \'diagnosticFindings\'.\\n"', '"PASO 3 (Análisis Visual y Fenotipado Profundo): Analiza las imágenes basándose PRINCIPALMENTE en el \'REPORTE DEL ESCÁNER VISUAL\' superior para evitar ceguera focal. Si el reporte del Escáner dice que la homogeneidad bilateral presenta distorsión y un órgano está \'Borrado/Fusionado\' o el plano de clivaje está interrumpido, ESTÁS OBLIGADO a usar la Ley de Causalidad Tisular (Ley 17). Detalla anomalías en \'diagnosticFindings\'.\\n" + "  ** CAPA 1 (OBSERVACIÓN PURA SIN DIAGNÓSTICO - Agnosia Forzada): Empieza describiendo obligatoriamente la geometría (contornos lisos vs lobulados), el número de masas y las densidades, CEDIENDO el control visual al Escáner Ojo. Tienes PROHIBIDO usar nombres patológicos.\\n" + "  *) REGLA DEL ESCRUTINIO 3x3 (PERIFERIA ANTES QUE CENTRO): Verifica explícitamente la arquitectura de los cuadrantes periféricos leyendo la \'Auditoría Lateral\' del Ojo Agnóstico ANTES de describir la masa o anomalía central. Usa este barrido para romper el sesgo de fijación visual.\\n"')

# Fix Sub-regla 11
old_rule = '"10. Sub-regla de Coherencia Terapéutica Post-Refutación (Vacuna contra el Arrastre / Leakage Vaccine): Si tu auditoría anula o degrada el diagnóstico inicial en favor de una variante benigna, quística o no quirúrgica (ej: de Schwannoma a Meningocele o Quiste de Tarlov), estás OBLIGADO a actualizar también la Prioridad de Intervención (correctedInterventionPriority) y la Agrupación Sindromática (correctedSyndromes) para que recomienden un manejo clínico conservador de vigilancia activa. 🛡️ VACUNA CONTRA EL ARRASTRE DE CONTEXTO: Tienes estrictamente prohibido copiar, heredar o arrastrar la urgencia o la acción del reporte del médico de primer nivel si has vetado su diagnóstico. Si has clasificado la lesión como de manejo conservador o variante benigna asintomática, estás obligado a reescribir de raíz correctedInterventionPriority, forzando la urgencia a \'moderada\' o \'baja\' y la Acción Cero a \'Vigilancia clínica neurológica y/o resonancia de control\'. Cualquier contradicción donde recomiendes cirugía en Acción Cero pero digas que es benigna no quirúrgica en el tratamiento será penalizada como un fallo crítico de lógica médica.\\n\\n"'
new_rule = '"10. Sub-regla de Coherencia Terapéutica Post-Refutación (Vacuna contra el Arrastre / Leakage Vaccine): Si tu auditoría anula o degrada el diagnóstico inicial en favor de una variante benigna, quística o no quirúrgica (ej: de Schwannoma a Meningocele o Quiste de Tarlov), estás OBLIGADO a actualizar también la Prioridad de Intervención (correctedInterventionPriority) y la Agrupación Sindromática (correctedSyndromes) para que recomienden un manejo clínico conservador de vigilancia activa. 🛡️ VACUNA CONTRA EL ARRASTRE DE CONTEXTO: Tienes estrictamente prohibido copiar, heredar o arrastrar la urgencia o la acción del reporte del médico de primer nivel si has vetado su diagnóstico. Si has clasificado la lesión como de manejo conservador o variante benigna asintomática, estás obligado a reescribir de raíz correctedInterventionPriority, forzando la urgencia a \'moderada\' o \'baja\' y la Acción Cero a \'Vigilancia clínica neurológica y/o resonancia de control\'. Cualquier contradicción donde recomiendes cirugía en Acción Cero pero digas que es benigna no quirúrgica en el tratamiento será penalizada como un fallo crítico de lógica médica.\\n" + "11. Sub-regla del Lumen y Deformación (Efecto de Masa Inversa): Audita implacablemente si el adscrito asumió un origen vascular primario (ej. Aneurisma) sin poder ubicar la \'luz verdadera\' del vaso separada de la masa, o si no pudo explicar la gran deformación/invasión de los órganos sólidos glandulares vecinos. Si es imposible delimitar la continuidad vascular lisa, o la anatomía colindante está distorsionada por un patrón lobulado/confluyente, DEBES VETAR el diagnóstico vascular y proponer obligatoriamente \'Masa infiltrativa/conglomerado de etiología a determinar\'.\\n\\n"'
content = content.replace(old_rule, new_rule)

# Fix run_debate timeout
content = content.replace('run_debate, 60000,', 'run_debate, 120000,')

with open(file_path, 'w', encoding='utf-8') as f:
    f.write(content)
print("Done patching gemini_core.py!")
